### ISSUE TITLE
Can this app be used along with other apps that tweak kernel?

### ISSUE THREAD

**Issue by js-d-coder** [frap129/spectrum#15]
Hi,
Thanks for your app, very useful.
I was wondering how exactly your app works? I mean can it be used with other apps that tweak kernel like [Kernel Adiutor](https://play.google.com/store/apps/details?id=com.grarak.kerneladiutor&hl=en_IN)? I use this app to change CPU governer, IO scheduler and enable wake on touble tap and fast charging.
I want to make sure these app don't conflict each other?
Thanks...

**Comment by frap129** [comment]
yes they can
